version: "3.7"
services:
  postgres:
    image: postgres:15.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
